---
- name: Restart Reloader Deployment
  ansible.builtin.include_role:
    name: dev_infra.deployment.k8s_deployment
    tasks_from: rollout_restart
  vars:
    dev_infra_deployment_restart_kind: Deployment
    dev_infra_deployment_restart_namespace: "{{ dev_infra_deployment_reloader_namespace }}"
    dev_infra_deployment_restart_name: "{{ dev_infra_deployment_reloader_deployment_name }}"

- name: Verify Reloader after restart
  ansible.builtin.import_tasks: verify.yml
