---
- name: Uninstall Reloader Helm release
  ansible.builtin.include_role:
    name: dev_infra.deployment.k8s_deployment
    tasks_from: helm_uninstall
  vars:
    dev_infra_deployment_helm_release_name: "{{ dev_infra_deployment_reloader_release_name }}"
    dev_infra_deployment_helm_namespace: "{{ dev_infra_deployment_reloader_namespace }}"

- name: Delete Reloader Pods before namespace deletion
  ansible.builtin.include_role:
    name: dev_infra.deployment.k8s_deployment
    tasks_from: delete_labelled
  vars:
    dev_infra_deployment_delete_kind: Pod
    dev_infra_deployment_delete_namespace: "{{ dev_infra_deployment_reloader_namespace }}"
    dev_infra_deployment_delete_label_selectors:
      - "{{ dev_infra_deployment_reloader_pod_selector }}"
    dev_infra_deployment_delete_options:
      gracePeriodSeconds: 0
    dev_infra_deployment_delete_wait_sleep: "{{ dev_infra_deployment_pod_wait_sleep_seconds }}"

- name: Delete Reloader namespace
  ansible.builtin.include_role:
    name: dev_infra.deployment.k8s_deployment
    tasks_from: delete_namespace
  vars:
    dev_infra_deployment_delete_namespace: "{{ dev_infra_deployment_reloader_namespace }}"
