---
- name: Skip Helm repository update in check mode
  ansible.builtin.debug:
    msg: "Skipping Helm repository {{ dev_infra_deployment_helm_repo_name }} update in check mode."
  when: ansible_check_mode
  delegate_to: localhost
  become: false
  run_once: true

- name: Configure Helm repository on the Ansible control node
  block:
    - name: Add Helm repository {{ dev_infra_deployment_helm_repo_name }}
      kubernetes.core.helm_repository:
        binary_path: "{{ dev_infra_deployment_helm_bin }}"
        name: "{{ dev_infra_deployment_helm_repo_name }}"
        repo_url: "{{ dev_infra_deployment_helm_repo_url }}"
        force_update: true

    - name: Update Helm repository {{ dev_infra_deployment_helm_repo_name }}
      ansible.builtin.command:
        argv:
          - "{{ dev_infra_deployment_helm_bin }}"
          - repo
          - update
          - "{{ dev_infra_deployment_helm_repo_name }}"
      changed_when: false
  when: not ansible_check_mode
  delegate_to: localhost
  become: false
  run_once: true
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
