---
- name: Patch Kubernetes resource from the Ansible control node
  kubernetes.core.k8s:
    kubeconfig: "{{ dev_infra_deployment_control_node_kubeconfig_path }}"
    state: present
    api_version: "{{ dev_infra_deployment_patch_api_version }}"
    kind: "{{ dev_infra_deployment_patch_kind }}"
    namespace: "{{ dev_infra_deployment_patch_namespace | default(omit) }}"
    name: "{{ dev_infra_deployment_patch_name }}"
    definition: "{{ dev_infra_deployment_patch_definition }}"
    merge_type:
      - strategic-merge
      - merge
  delegate_to: localhost
  become: false
  run_once: true
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
