---
- name: Kickstart stateful workloads
  hosts: k8s_workload_mgr
  become: false
  gather_facts: false
  pre_tasks:
    - name: Validate Ansible control node and Kubernetes API access
      ansible.builtin.import_role:
        name: dev_infra.deployment.k8s_deployment
        tasks_from: validate_control_node
      tags: [always]
  tasks:
    - name: Kickstart stateful workloads from the Ansible control node
      block:
        - name: Initialize or unseal Vault
          ansible.builtin.import_role:
            name: dev_infra.deployment.vault
            tasks_from: kickstart
          tags: [vault]

        - name: Kickstart OpenSearch post-deployment state
          ansible.builtin.import_role:
            name: dev_infra.deployment.opensearch
            tasks_from: kickstart
          tags: [opensearch]
      delegate_to: localhost
      become: false
      run_once: true
